import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ContactForm } from "@/components/ContactForm"
import { Phone, Mail, MapPin, ArrowLeft } from "lucide-react"
import Link from "next/link"
import Image from "next/image"

// Privacy Policy Page Component
export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 h-16">
        <div className="container mx-auto px-5">
          <div className="flex h-16 items-center justify-between">
            <div className="flex items-center gap-1">
              <Link href="/">
                <Image
                  src="/glass-house-logo.png"
                  alt="Glass House Recovery Logo"
                  width={40}
                  height={40}
                  className="h-10 w-auto"
                />
              </Link>
              <Link href="/" className="text-2xl font-bold tracking-tighter">
                Glass House
              </Link>
            </div>
            <nav className="hidden md:flex items-center space-x-6 text-sm font-medium">
              <Link href="/about" className="text-muted-foreground hover:text-foreground">About</Link>
              <Link href="/programs" className="text-muted-foreground hover:text-foreground">Programs</Link>
              <Link href="/admissions" className="text-muted-foreground hover:text-foreground">Admissions</Link>
              <Link href="/referrals" className="text-muted-foreground hover:text-foreground">Referrals</Link>
              <Link href="/contact" className="text-muted-foreground hover:text-foreground">Contact</Link>
              <Link href="/newsletter" className="text-muted-foreground hover:text-foreground">Newsletter</Link>
            </nav>
          </div>
        </div>
      </header>

      <main className="py-12">
        <div className="container mx-auto px-5">
          {/* Back Button */}
          <div className="mb-8">
            <Button variant="ghost" asChild className="gap-2">
              <Link href="/">
                <ArrowLeft className="h-4 w-4" />
                Back to Home
              </Link>
            </Button>
          </div>

          {/* Privacy Policy Content */}
          <div className="max-w-4xl mx-auto">
            <div className="mb-12">
              <h1 className="text-4xl md:text-5xl font-bold tracking-tighter mb-6">Privacy Policy</h1>
              <p className="text-muted-foreground text-lg">Effective date: November 1, 2021</p>
            </div>

            <div className="prose prose-lg max-w-none">
              <p className="text-lg leading-relaxed mb-8">
                Glass House Recovery LLC ("us", "we", or "our") operates the https://glasshouserecovery.com website (hereinafter referred to as the "Service").
              </p>
              
              <p className="text-lg leading-relaxed mb-8">
                This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.
              </p>
              
              <p className="text-lg leading-relaxed mb-12">
                We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://glasshouserecovery.com
              </p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Definitions</h2>
              
              <h3 className="text-2xl font-semibold mb-4">Service</h3>
              <p className="mb-6">Service is the https://glasshouserecovery.com website operated by Glass House Recovery LLC</p>
              
              <h3 className="text-2xl font-semibold mb-4">Personal Data</h3>
              <p className="mb-6">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
              
              <h3 className="text-2xl font-semibold mb-4">Usage Data</h3>
              <p className="mb-6">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
              
              <h3 className="text-2xl font-semibold mb-4">Cookies</h3>
              <p className="mb-8">Cookies are small files stored on your device (computer or mobile device).</p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Types of Data Collected</h2>
              
              <h3 className="text-2xl font-semibold mb-4">Personal Data</h3>
              <p className="mb-4">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
              <ul className="list-disc pl-6 mb-6 space-y-2">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
              </ul>
              
              <h3 className="text-2xl font-semibold mb-4">Usage Data</h3>
              <p className="mb-6">We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
              
              <h3 className="text-2xl font-semibold mb-4">Tracking & Cookies Data</h3>
              <p className="mb-4">We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
              <p className="mb-4">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>
              <p className="mb-4">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
              
              <h4 className="text-xl font-semibold mb-4">Examples of Cookies we use:</h4>
              <ul className="list-disc pl-6 mb-8 space-y-2">
                <li><strong>Session Cookies</strong> – We use Session Cookies to operate our Service.</li>
                <li><strong>Preference Cookies</strong> – We use Preference Cookies to remember your preferences and various settings.</li>
                <li><strong>Security Cookies</strong> – We use Security Cookies for security purposes.</li>
              </ul>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Use of Data</h2>
              <p className="mb-4">Glass House Recovery LLC uses the collected data for various purposes:</p>
              <ul className="list-disc pl-6 mb-8 space-y-2">
                <li>To provide and maintain our Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide customer support</li>
                <li>To gather analysis or valuable information so that we can improve our Service</li>
                <li>To monitor the usage of our Service</li>
                <li>To detect, prevent and address technical issues</li>
              </ul>

              <h3 className="text-2xl font-semibold mb-4">Transfer of Data</h3>
              <p className="mb-4">Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
              <p className="mb-4">If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>
              <p className="mb-4">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
              <p className="mb-8">Glass House Recovery LLC will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Disclosure of Data</h2>
              
              <h3 className="text-2xl font-semibold mb-4">Disclosure for Law Enforcement</h3>
              <p className="mb-6">Under certain circumstances, Glass House Recovery LLC may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
              
              <h3 className="text-2xl font-semibold mb-4">Legal Requirements</h3>
              <p className="mb-4">Glass House Recovery LLC may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
              <ul className="list-disc pl-6 mb-6 space-y-2">
                <li>To comply with a legal obligation</li>
                <li>To protect and defend the rights or property of Glass House Recovery LLC</li>
                <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>To protect the personal safety of users of the Service or the public</li>
                <li>To protect against legal liability</li>
              </ul>
              
              <h3 className="text-2xl font-semibold mb-4">Security of Data</h3>
              <p className="mb-8">The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Service Providers</h2>
              <p className="mb-8">We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Analytics</h2>
              <p className="mb-6">We may use third-party Service Providers to monitor and analyse the use of our Service.</p>
              
              <h3 className="text-2xl font-semibold mb-4">Google Analytics</h3>
              <p className="mb-4">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</p>
              <p className="mb-4">You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.</p>
              <p className="mb-8">For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en" className="text-blue-600 hover:underline">https://policies.google.com/privacy?hl=en</a></p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Links to Other Sites</h2>
              <p className="mb-4">Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
              <p className="mb-8">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Children's Privacy</h2>
              <p className="mb-4">Our Service does not address anyone under the age of 18 ("Children").</p>
              <p className="mb-4">We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Changes to This Privacy Policy</h2>
              <p className="mb-4">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
              <p className="mb-4">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
              <p className="mb-8">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Contact Us</h2>
              <p className="mb-4">If you have any questions about this Privacy Policy, please contact us:</p>
              <div className="bg-muted/50 p-6 rounded-lg mb-8">
                <p className="font-semibold">Glass House Recovery LLC</p>
                <p>8318 Forrest Street, Suite 100</p>
                <p>Ellicott City, MD 20143</p>
                <p>410-970-4842</p>
                <p>info@glasshouserecovery.com</p>
              </div>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">HIPAA Notice</h2>
              <p className="mb-6">This notice describes how medical information about you may be used and disclosed and how you can get access to this information. <strong>Please review it carefully.</strong></p>

              <h3 className="text-2xl font-semibold mb-4">Your Rights</h3>
              <p className="mb-4">You have the right to:</p>
              <ul className="list-disc pl-6 mb-6 space-y-2">
                <li>Get a copy of your health and claims records</li>
                <li>Correct your health and claims records</li>
                <li>Request confidential communication</li>
                <li>Ask us to limit the information we share</li>
                <li>Get a list of those with whom we've shared your information</li>
                <li>Get a copy of this privacy notice</li>
                <li>Choose someone to act for you</li>
                <li>File a complaint if you believe your privacy rights have been violated</li>
              </ul>

              <h3 className="text-2xl font-semibold mb-4">Your Choices</h3>
              <p className="mb-4">You have some choices in the way that we use and share information as we:</p>
              <ul className="list-disc pl-6 mb-8 space-y-2">
                <li>Answer coverage questions from your family and friends</li>
                <li>Provide disaster relief</li>
                <li>Market our services and sell your information</li>
              </ul>

              <h3 className="text-2xl font-semibold mb-4">Our Uses and Disclosures</h3>
              <p className="mb-4">We may use and share your information as we:</p>
              <ul className="list-disc pl-6 mb-8 space-y-2">
                <li>Help manage the health care treatment you receive</li>
                <li>Run our organization</li>
                <li>Pay for your health services</li>
                <li>Administer your health plan</li>
                <li>Help with public health and safety issues</li>
                <li>Do research</li>
                <li>Comply with the law</li>
                <li>Respond to organ and tissue donation requests and work with a medical examiner or funeral director</li>
                <li>Address workers' compensation, law enforcement, and other government requests</li>
                <li>Respond to lawsuits and legal actions</li>
              </ul>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">SMS Communications</h2>
              <p className="mb-4">No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. All other categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.</p>
              <p className="mb-4">By providing your phone number, you consent to receive SMS messages from Glass House Recovery related to admissions, scheduling, and general inquiries. Message frequency may vary. Message and data rates may apply.</p>
              <p className="mb-8">You may opt out at any time by replying STOP. For more information, reply HELP or contact us through our website.</p>

              <h2 className="text-3xl font-bold tracking-tighter mb-6">Changes to the Terms of this Notice</h2>
              <p className="mb-8">We can change the terms of this notice, and the changes will apply to all information we have about you. The new notice will be available upon request, on our web site, and we will mail a copy to you.</p>

              <div className="bg-muted/50 p-6 rounded-lg mb-8">
                <p className="font-semibold">Glass House Recovery</p>
                <p>8318 Forrest St</p>
                <p>Suite 100</p>
                <p>Ellicott City, MD 21043</p>
                <p className="font-semibold">410.970.3374 (call/text)</p>
                <p>Let Fax Die.</p>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-background">
        <div className="container mx-auto px-5">
          <div className="py-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-4">
              <div>
                <h3 className="font-bold mb-0">Glass House Recovery</h3>
                <div className="space-y-2 text-sm text-muted-foreground">
                  <div className="flex items-start gap-6">
                    <div className="flex items-start gap-2">
                      <MapPin className="w-4 h-4 mt-0.5 flex-shrink-0" />
                      <div>
                        8318 Forrest St, Suite 100<br />
                        Ellicott City, MD 21043
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Phone className="w-4 h-4 flex-shrink-0" />
                      <div className="text-muted-foreground">
                        410.970.3374
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div></div>

              <div className="text-center">
                <Button className="mb-4" asChild>
                  <a href="/contact">SUBSCRIBE TO NEWSLETTER</a>
                </Button>
                <div className="flex justify-center space-x-4 text-sm">
                  <a href="https://www.facebook.com/glasshouserecovery/" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                    Facebook
                  </a>
                  <a href="https://www.instagram.com/glasshouserecovery/" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                    Instagram
                  </a>
                  <a href="https://www.linkedin.com/company/glasshouserecovery/" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                    LinkedIn
                  </a>
                </div>
              </div>
            </div>
          </div>
          <div className="py-3 relative text-center text-sm text-muted-foreground">
            <Link href="/privacy-policy" className="absolute left-0 hover:text-foreground">Privacy Policy</Link>
            <p>© 2025 Glass House</p>
          </div>
        </div>
      </footer>
    </div>
  )
} 